# Generated by Django 2.2.6 on 2020-08-04 19:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0009_auto_20200802_2006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': (('-pub_date',),)},
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('user', 'author')},
        ),
    ]
